// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
using Microsoft.Teams.Bot.Apps;
using Microsoft.Teams.Bot.Apps.Handlers;
using Microsoft.Teams.Bot.Apps.Schema;
using System.Text.Json;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddTeams();

var app = builder.Build();
var teams = app.UseTeams();

teams.OnMessage(async (context, cancellationToken) =>
{
    var text = context.Activity.Text?.Trim().ToLower() ?? "";

    if (text.Contains("label"))
        await SendAILabel(context);
    else if (text.Contains("feedback"))
        await SendFeedbackButtons(context);
    else if (text.Contains("sensitivity"))
        await SendSensitivityLabel(context);
    else if (text.Contains("citation"))
        await SendCitations(context);
    else
        await SendWelcomeCard(context);
});

//teams.OnFeedback(async (context, cancellationToken) =>
//{
//    var reaction = "No reaction";
//    var feedbackText = "No feedback was provided.";

//    var actionValue = context.Activity.Value.ActionValue;
//    if (actionValue != null)
//    {
//        var json = JsonSerializer.Serialize(actionValue);
//        using var doc = JsonDocument.Parse(json);
//        var root = doc.RootElement;

//        if (root.TryGetProperty("reaction", out var reactionProp))
//            reaction = reactionProp.GetString() ?? "No reaction";

//        if (root.TryGetProperty("feedback", out var feedbackProp))
//        {
//            var feedbackJsonStr = feedbackProp.GetString();
//            if (!string.IsNullOrEmpty(feedbackJsonStr))
//            {
//                using var feedbackDoc = JsonDocument.Parse(feedbackJsonStr);
//                if (feedbackDoc.RootElement.TryGetProperty("feedbackText", out var ftProp))
//                    feedbackText = ftProp.GetString() ?? "No feedback was provided.";
//            }
//        }
//    }

//    await context.Send($"Provided reaction: {reaction}<br> Feedback: {feedbackText}");
//});

async Task SendAILabel(Context<MessageActivity> context)
{
    var msg = new MessageActivity
    {
        Text = "Hi, this message is generated by AI"
    };
    msg.AddAIGenerated();
    await context.SendActivityAsync(msg);
}

async Task SendFeedbackButtons(Context<MessageActivity> context)
{
    await context.SendActivityAsync(new MessageActivity("This is an example of a feedback button - this helps to provide feedback for a message")
        .AddFeedback());
}

async Task SendSensitivityLabel(Context<MessageActivity> context)
{
    var entity = new CitationEntity();
    entity.Properties["@id"] = "";
    entity.Properties["usageInfo"] = JsonSerializer.SerializeToNode(new SensitiveUsageEntity
    {
        Name = "Confidential \\ Contoso FTE",
        Description = "Please be mindful of sharing outside of your team"
    });

    await context.SendActivityAsync(new MessageActivity
    {
        Text = "This is an example of a sensitivity label that help users identify the confidentiality of a message",
        Entities = [entity]
    });
}

async Task SendCitations(Context<MessageActivity> context)
{
    var message = new MessageActivity
    {
        Text = "Hey I'm a friendly AI bot. This message is generated through AI [1]"
    };

    message.AddCitation(1, new CitationAppearance
    {
        Name = "AI messages bot",
        Url = new Uri("https://example.com/claim-1"),
        Abstract = "Excerpt description",
        Keywords = new List<string> { "keyword 1", "keyword 2", "keyword 3" },
        Icon = CitationIcon.MicrosoftWord
    });

    await context.SendActivityAsync(message);
}

async Task SendWelcomeCard(Context<MessageActivity> context)
{
    await context.SendActivityAsync("Welcome to the AI bot! Try sending messages with keywords like 'label', 'sensitivity', 'feedback', or 'citation' to see different AI features.");
}

app.Run();